# Backend configuration
backend:
  name: nicolasvila-backend-app
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0
  containerPort: 8080
  host: nicolas-vila.codelab.cloud-sp.eu
  service:
    port: 443